[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    'base64-sol/=lib/base64-sol/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@uniswap/v2-core/=lib/v2-core/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
    '@uniswap/v3-staker/=lib/v3-staker/',
    '@uniswap/swap-router-contracts/=lib/swap-router-contracts/',
    '@uniswap/lib/=lib/solidity-lib/',
  ]
optimizer_runs = 800
bytecode_hash = "none"
fs_permissions = [
  { access = "read-write", path = "./artifacts/"}
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
